import { BoardSpaceEnum } from './GameEnums';
import SquareModel from '../model/Square-Model';

export const INIT_GAME_SETUP = [
    [ new SquareModel(BoardSpaceEnum.SAFE_ZONE), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), 
      new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.SAFE_ZONE) ],
    [ new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY) ],
    [ new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY) ],
    [ new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.WHITE_VIKING), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY),
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER) ],
    [ new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.WHITE_VIKING), 
      new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER) ],
    [ new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.WHITE_KING), 
      new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER) ],
    [ new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.WHITE_VIKING), 
      new SquareModel(BoardSpaceEnum.WHITE_VIKING), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER) ],
    [ new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.WHITE_VIKING), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER) ],
    [ new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY) ],
    [ new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY) ],
    [ new SquareModel(BoardSpaceEnum.SAFE_ZONE), new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), 
      new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.BLACK_ATTACKER), new SquareModel(BoardSpaceEnum.EMPTY), 
      new SquareModel(BoardSpaceEnum.EMPTY), new SquareModel(BoardSpaceEnum.SAFE_ZONE) ]
];